{% set version = "0.5.0" %}

package:
  name: sphinx-autodoc2-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-autodoc2/sphinx_autodoc2-{{ version }}.tar.gz
  sha256: 7d76044aa81d6af74447080182b6868c7eb066874edc835e8ddf810735b6565a

build:
  number: 1
  noarch: python

requirements:
  host:
    - python >=3.8
  run:
    - python >=3.8

outputs:
  - name: sphinx-autodoc2
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - autodoc2 = autodoc2.cli:app_main
    requirements:
      host:
        - flit-core >=3.2,<4
        - pip
        - python >=3.8
      run:
        - astroid >=2.7,<4
        - python >=3.8
        - tomli
        - typing_extensions
    test:
      imports:
        - autodoc2
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/sphinx-extensions2/sphinx-autodoc2
      summary: Analyse a python project and create documentation for it.
      license: MIT
      license_file: LICENSE
      doc_url: https://sphinx-autodoc2.readthedocs.io

  - name: sphinx-autodoc2-with-cli
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage('sphinx-autodoc2', max_pin='x.x.x') }}
        - python >=3.8
        - typer
    test:
      source_files:
        - tests
      imports:
        - autodoc2
      commands:
        - pip check
        - autodoc2 --help
        - pytest -vv --cov=autodoc2 --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=63 -k "not sphinx_build_directives"
      requires:
        - pip
        - pytest-cov
        - pytest-regressions
        - sphinx >=4.0,<7

about:
  home: https://github.com/sphinx-extensions2/sphinx-autodoc2
  summary: Analyse a python project and create documentation for it.
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-autodoc2.readthedocs.io

extra:
  feedstock-name: sphinx-autodoc2
  recipe-maintainers:
    - conda-forge/sphinx
    - bollwyvl
